### ISSUE TITLE
On the issue of network weight sharing during training

### ISSUE THREAD

**Issue by November666** [fityanul/SDAN-for-Rain-Removal#1]
Hello, thank you very much for sharing your code，but i do not konw how the weigth shared during training

**Comment by fityanul** [comment]
> Hello, thank you very much for sharing your code，but i do not konw how the weigth shared during training

Hi @November666 ,
Thank You very much for asking.

Can You explain more details about the question? Do You mean the weight shared between two sequential networks?

Thank You

**Comment by November666** [comment]
Yes，But I have figured it out,thank you for your reply&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fityanul/SDAN-for-Rain-Removal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 上午9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fityanul/SDAN-for-Rain-Removal] On the issue of network weight sharing during training (#1)





  
Hello, thank you very much for sharing your code，but i do not konw how the weigth shared during training
  
Hi @November666 ,
 Thank You very much for asking.
 
Can You explain more details about the question? Do You mean the weight shared between two sequential networks?
 
Thank You

**Comment by fityanul** [comment]
> Yes，But I have figured it out,thank you for your reply&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fityanul/SDAN-for-Rain-Removal" ***@***.***&gt;; 发送时间:&nbsp;2021年5月20日(星期四) 上午9:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [fityanul/SDAN-for-Rain-Removal] On the issue of network weight sharing during training (#1) Hello, thank you very much for sharing your code，but i do not konw how the weigth shared during training Hi @November666 , Thank You very much for asking. Can You explain more details about the question? Do You mean the weight shared between two sequential networks? Thank You — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

You are welcome @November666
